# Generated by Django 5.0 on 2026-03-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiadoars', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('tipo_doacao', models.CharField(max_length=100)),
            ],
        ),
    ]
