# Generated by Django 5.0 on 2026-03-19 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiadoars', '0003_instituicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'ordering': ['nome'], 'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='tipo_doacao',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa?'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='cep',
            field=models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituicao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='site',
            field=models.URLField(blank=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='tipo_instituicao',
            field=models.CharField(choices=[('abrigo', 'Abrigo'), ('ong', 'ONG'), ('igreja', 'Igreja'), ('escola', 'Escola'), ('hospital', 'Hospital'), ('outro', 'Outro')], default='ong', max_length=20, verbose_name='Tipo de Instituição'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='tipos_doacao',
            field=models.CharField(blank=True, help_text='Separe por vírgula. Ex: roupas, alimentos, brinquedos', max_length=200, verbose_name='Tipos de doação aceitos'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome da Instituição'),
        ),
    ]
