# Generated by Django 5.0 on 2026-04-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiadoars', '0004_alter_instituicao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('personalizada', models.BooleanField(default=False, verbose_name='Categoria personalizada?')),
            ],
            options={
                'verbose_name': 'Categoria de Doação',
                'verbose_name_plural': 'Categorias de Doação',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='tipos_doacao',
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='categorias_doacao',
            field=models.ManyToManyField(blank=True, help_text='Selecione uma ou mais categorias', to='guiadoars.categoriadoacao', verbose_name='Categorias de doação aceitas'),
        ),
    ]
