# Generated by Django 5.0 on 2026-04-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiadoars', '0005_categoriadoacao_remove_instituicao_tipos_doacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='horario_funcionamento',
            field=models.TextField(blank=True, help_text='Ex: Segunda a sexta, 8h às 18h; Sábado, 8h às 12h', verbose_name='Horário de funcionamento'),
        ),
    ]
