# Generated by Django 5.0 on 2026-04-10 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiadoars', '0006_instituicao_horario_funcionamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='horario_funcionamento',
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('abertura', models.TimeField(verbose_name='Abre às')),
                ('fechamento', models.TimeField(verbose_name='Fecha às')),
                ('intervalo_inicio', models.TimeField(blank=True, null=True, verbose_name='Intervalo (início)')),
                ('intervalo_fim', models.TimeField(blank=True, null=True, verbose_name='Intervalo (fim)')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='guiadoars.instituicao')),
            ],
            options={
                'verbose_name': 'Horário de funcionamento',
                'verbose_name_plural': 'Horários de funcionamento',
                'ordering': ['instituicao', 'dia_semana'],
            },
        ),
    ]
