# Generated by Django 5.0 on 2026-05-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guiadoars', '0007_remove_instituicao_horario_funcionamento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
