# Generated by Django 5.0 on 2026-05-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiadoars', '0008_remove_topic_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Instituição')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('tipo_instituicao', models.CharField(choices=[('abrigo', 'Abrigo'), ('ong', 'ONG'), ('igreja', 'Igreja'), ('escola', 'Escola'), ('hospital', 'Hospital'), ('outro', 'Outro')], default='ong', max_length=20, verbose_name='Tipo de Instituição')),
                ('categorias_doacao_texto', models.TextField(blank=True, help_text='Ex: Roupas, Alimentos, Brinquedos', verbose_name='Tipos de doação aceitos')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('observacao_admin', models.TextField(blank=True, verbose_name='Observação do administrador')),
            ],
            options={
                'verbose_name': 'Sugestão de Instituição',
                'verbose_name_plural': 'Sugestões de Instituições',
                'ordering': ['-data_envio'],
            },
        ),
    ]
